server:
  port: 19099

spring:
  application:
    name: delivery-history
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/deliveryhistory
    username: 4jdelivery
    password: 4jsystem
  second-datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/hub
    username: 4jdelivery
    password: 4jsystem

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
message:
  exchange: forj
  queue:
    delivery: forj.delivery
    delivery-history: forj.delivery-history
    complete:
      delivery: forj.complete.delivery
      order: forj.complete.order
  complete:
    exchange: forj.complete