spring:
  application:
    name: hub
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  config:
    import:
      - optional:classpath:application-jwt.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19092/eureka/

server:
  port: 19092
