server:
  port: 19096

spring:
  application:
    name: product
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

feign:
  naver:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
    url: ${NAVER_URL}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    preferIpAddress: true

message:
  forj:
    exchange: ${MESSAGE_FORJ_EXCHANGE}
    queue:
      product: ${MESSAGE_QUEUE_FORJ_PRODUCT}
      delivery: ${MESSAGE_QUEUE_FORJ_DELIVERY}
      delivery-history: ${MESSAGE_QUEUE_FORJ_DELIVERY_HISTORY}
  complete:
    exchange: ${MESSAGE_COMPLETE_EXCHANGE}
    queue:
      delivery: ${MESSAGE_QUEUE_COMPLETE_DELIVERY}
      order: ${MESSAGE_QUEUE_COMPLETE_ORDER}
  cancel:
    exchange: ${MESSAGE_CANCEL_EXCHANGE}
    queue:
      product: ${MESSAGE_QUEUE_CANCEL_PRODUCT}
  error:
    exchange: ${MESSAGE_ERROR_EXCHANGE}
    queue:
      order: ${MESSAGE_QUEUE_ERROR_ORDER}

