version: '3.8'

networks:
  delivery-system-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: test-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ai
    ports:
      - "5432:5432"
    networks:
      - delivery-system-network
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/

  redis:
    image: redis:latest
    container_name: test-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - delivery-system-network

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: test-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - delivery-system-network