version: '3.8'

networks:
  delivery-system-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ai
    ports:
      - "5432:5432"
    networks:
      - delivery-system-network
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
