server:
  port: 19097

spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: 4jdelivery
    password: 4jsystem
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

message:
  forj:
    exchange: forj
    queue:
      product: forj.product
      delivery: forj.delivery
      delivery-history: forj.delivery-history
  complete:
    exchange: forj.complete
    queue:
      delivery: complete.delivery
      order: complete.order
  cancel:
    exchange: forj.cancel
    queue:
      product: cancel.product
  error:
    exchange: forj.error
    queue:
      order: error.order



