server:
  port: 19097

spring:
  application:
    name: order
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

message:
  exchange: ${RABBITMQ_FORJ_EXCHANGE}
  queue:
    product: ${RABBITMQ_FORJ_PRODUCT_QUEUE}
    delivery-history: ${RABBITMQ_FORJ_DELIVERY_HISTORY_QUEUE}
    complete:
      delivery: ${RABBITMQ_COMPLETE_DELIVERY_EXCHANGE}
      order: ${RABBITMQ_COMPLETE_ORDER_EXCHANGE}
  complete:
    exchange: ${RABBITMQ_COMPLETE_EXCHANGE}

