server:
  port: 19097

spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: 4jdelivery
    password: 4jsystem
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

message:
  forj:
    exchange: ${MESSAGE_FORJ_EXCHANGE}
    queue:
      product: ${MESSAGE_QUEUE_FORJ_PRODUCT}
      delivery: ${MESSAGE_QUEUE_FORJ_DELIVERY}
      delivery-history: ${MESSAGE_QUEUE_FORJ_DELIVERY_HISTORY}
  complete:
    exchange: ${MESSAGE_COMPLETE_EXCHANGE}
    queue:
      delivery: ${MESSAGE_QUEUE_COMPLETE_DELIVERY}
      order: ${MESSAGE_QUEUE_COMPLETE_ORDER}
  cancel:
    exchange: ${MESSAGE_CANCEL_EXCHANGE}
    queue:
      product: ${MESSAGE_QUEUE_CANCEL_PRODUCT}
  error:
    exchange: ${MESSAGE_ERROR_EXCHANGE}
    queue:
      order: ${MESSAGE_QUEUE_ERROR_ORDER}



