spring:
  application:
    name: ai
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  config:
    import:
      - optional:classpath:application-ai.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19101

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
    feign: DEBUG
